In [2]:
from typing import List, Dict
from collections import Counter
import torch
import math

In [8]:
bo = {0: torch.Tensor([10]), 1: torch.Tensor([20])}
box = list(bo.values())
print(box)


[tensor([10.]), tensor([20.])]


In [20]:
to = torch.ones(2)
to[1] = 2
cosa = (torch.argmax(to)).item()
print(type(cosa))

<class 'int'>


In [3]:
params: torch.Tensor = torch.randn(9 + 1, 1)
for idx, count in enumerate(params):
    print(idx)
    print(count)

0
tensor([-1.0555])
1
tensor([0.8684])
2
tensor([1.6153])
3
tensor([-1.3084])
4
tensor([-0.6422])
5
tensor([0.1375])
6
tensor([-0.5112])
7
tensor([0.8743])
8
tensor([1.1818])
9
tensor([-2.0717])


In [20]:
features = torch.tensor([[1, 1, 0], [0, 1, 1], [1, 0, 1]], dtype=torch.float32)
labels = torch.tensor([0, 1, 1], dtype=torch.float32)
features@(labels.T)

tensor([1., 2., 1.])